export const PenalCode = [
  { charge: "(1)01. Intimidation" },
  { charge: "(1)02. Assault" },
  { charge: "(1)03. Assault With A Deadly Weapon" },
  { charge: "(1)04. Mutual Combat" },
  { charge: "(1)05. Battery" },
  { charge: "(1)06. Aggravated Battery" },
  { charge: "(1)07. Attempted Murder" },
  { charge: "(1)08. Manslaughter" },
  { charge: "(1)09. Murder" },
  { charge: "(1)10. False Imprisonment" },
  { charge: "(1)11. Kidnapping" },
  { charge: "(1)12. Mayhem" },
  { charge: "(1)13. Vehicular Murder" },
  { charge: "(2)01. Arson" },
  { charge: "(2)02. Trespassing " },
  { charge: "(2)03. Trespassing within a Restricted Zone" },
  { charge: "(2)04. Burglary" },
  { charge: "(2)05. Possession Of Burglary Tools" },
  { charge: "(2)06. Robbery" },
  { charge: "(2)07. Armed Robbery" },
  { charge: "(2)08. Petty Theft" },
  { charge: "(2)09. Theft" },
  { charge: "(2)10. Grand Theft" },
  { charge: "(2)11. Grand Theft Auto" },
  { charge: "(2)12. Grand Theft Of A Firearm" },
  { charge: "(2)13. Receiving Stolen Property" },
  { charge: "(2)14. Extortion" },
  { charge: "(2)15. Forgery" },
  { charge: "(2)16. Fraud" },
  { charge: "(2)17. Vandalism" },
  { charge: "(3)01. Lewd Or Dissolute Conduct In Public" },
  { charge: "(3)02. Indecent Exposure" },
  { charge: "(3)03. Prostitution" },
  { charge: "(3)04. Solicitation of Prostitution" },
  { charge: "(3)05. Pandering / Pimping" },
  { charge: "(3)06. Sexual Assault" },
  { charge: "(3)07. Sexual Battery" },
  { charge: "(3)08. Rape" },
  { charge: "(3)09. Statutory Rape" },
  { charge: "(3)10. Stalking" },
  { charge: "(4)01. Bribery" },
  { charge: "(4)02. Failure To Pay A Fine" },
  { charge: "(4)03. Contempt of Court***" },
  { charge: "(4)04. Subpoena Violation" },
  { charge: "(4)05. Dissuading A Witness Or Victim" },
  { charge: "(4)06. False Information To A Government Employee" },
  { charge: "(4)07. Filing A False Complaint" },
  { charge: "(4)08. Perjury" },
  { charge: "(4)09. Failure To Identify To A Peace Officer" },
  { charge: "(4)10. Impersonation Of A Government Employee" },
  { charge: "(4)11. Obstruction Of A Government Employee" },
  { charge: "(4)12. Resisting A Peace Officer" },
  { charge: "(4)13. Escape From Custody" },
  { charge: "(4)14. Escape" },
  { charge: "(4)15. Prisoner Breakout" },
  { charge: "(4)16. Human Trafficking" },
  { charge: "(4)17. Misuse Of A Government Hotline" },
  { charge: "(4)18. Tampering With Evidence" },
  { charge: "(4)19. Introduction Of Contraband" },
  { charge: "(4)20. Violation Of Parole Or Probation" },
  { charge: "(4)21. Voter Fraud / Voter Pandering" },
  { charge: "(4)22. Corruption Of Public Duty" },
  { charge: "(4)23. Corruption Of Public Office" },
  { charge: "(4)24. Contempt of Senate***" },
  { charge: "(5)01. Disturbing The Peace" },
  { charge: "(5)02. Unlawful Assembly" },
  { charge: "(5)03. Incitement To Riot" },
  { charge: "(5)04. Vigilantism" },
  { charge: "(5)05. Terrorism***" },
  { charge: "(6)01. Possession Of A Controlled Substance" },
  { charge: "(6)02. Possession Of A Controlled Substance With Intent To Sell" },
  { charge: "(6)03. Possession Of Drug Paraphernalia" },
  { charge: "(6)04. Maintaining A Place For The Purpose Of Distribution" },
  { charge: "(6)05. Manufacture Of A Controlled Substance" },
  { charge: "(6)06. Sale Of A Controlled Substance" },
  { charge: "(6)07. Possession Of An Open Container" },
  { charge: "(6)08. Public Intoxication" },
  { charge: "(6)09. Under The Influence Of A Controlled Substance" },
  { charge: "(6)10. Facial Obstruction While Committing A Crime" },
  { charge: "(6)11. Possession of Marijuana" },
  { charge: "(7)01. Animal Abuse / Cruelty" },
  { charge: "(7)02. Child Abuse" },
  { charge: "(7)03. Sale of Alcohol To A Minor" },
  { charge: "(7)04. Minor Alcohol Violation" },
  { charge: "(7)05. Possession Of Child Pornography" },
  { charge: "(8)01. Driving With A Suspended License" },
  { charge: "(8)02. Evading A Peace Officer" },
  { charge: "(8)03. Evading A Peace Officer — High Performance Vehicle" },
  { charge: "(8)04. Evading A Peace Officer — Oversized Vehicle" },
  { charge: "(8)05. Evading A Peace Officer — Naval Vessel" },
  { charge: "(8)06. Evading A Peace Officer — Aircraft" },
  { charge: "(8)07. Flying Without A Pilot's License" },
  { charge: "(8)08. Hit And Run" },
  { charge: "(8)09. Reckless Operation Of An Aircraft" },
  { charge: "(8)10. Reckless Operation Of An Off-Road Or Naval Vehicle" },
  { charge: "(8)11. Failure To Adhere To ATC Protocols" },
  { charge: "(8)12. Failure To Adhere To Flight Protocols" },
  { charge: "(8)13. Restricted Airspace Violation" },
  { charge: "(9)01. Possession Of A Prohibited Weapon" },
  { charge: "(9)02. Possession Of An Unlicensed Firearm" },
  { charge: "(9)03. Possession Of An Illegal Firearm" },
  { charge: "(9)04. Possession Of An Assault Weapon" },
  { charge: "(9)05. Unlicensed Distribution Of A Weapon" },
  { charge: "(9)06. Possession Of An Explosive Device" },
  { charge: "(9)07. Manufacture or Possession of an Improvised Device" },
  { charge: "(9)08. Possession of Weaponry With Intent To Sell" },
  { charge: "(9)09. Possession Of Explosive Devices With Intent To Sell" },
  { charge: "(9)10. Brandishing A Firearm" },
  { charge: "(9)11. Weapons Discharge Violation" },
  { charge: "(9)12. Drive-By Shooting" },
  { charge: "(9)13. CCW / PF Violation" },
  { charge: "(10)00. Exception" },
  { charge: "(10)01. Attempt" },
  { charge: "(10)02. Conspiracy" },
  { charge: "(10)03. Soliciting" },
  { charge: "(10)04. Government Worker Clause " },
  { charge: "(10)05. Plea Bargaining / Police Compliance Clause" },
  { charge: "(10)06. Three-strikes Vehicle Policy" },
  { charge: "(10)07. Criminal Accomplice Clause" },
  { charge: "(10)08. Accessory After the Fact" },
  { charge: "(10)09. Gang Crimes Clause" },
  { charge: "(11)01. Speeding Violation" },
  { charge: "(11)02. Failure To Abide To A Traffic Control Device" },
  { charge: "(11)03. Yield Violation" },
  { charge: "(11)04. Parking Violation" },
  { charge: "(11)05. Reckless Driving" },
  { charge: "(11)06. Vehicular Endangerment" },
  { charge: "(11)07. Vehicular Noise Violation" },
  { charge: "(11)08. Illegal Nitrous Oxide Possession" },
  { charge: "(11)09. Illegal Usage Of Hydraulics" },
  { charge: "(11)10. Driving While Impaired (DWI)" },
  { charge: "(11)11. Driving Under The Influence (DUI)" },
  { charge: "(11)12. Registration Violation" },
  { charge: "(11)13. Unsafe Usage Of A Bicycle" },
  { charge: "(11)14. Street Racing" },
  { charge: "(11)15. Driving without a Valid License" },
  { charge: "(11)16. Jaywalking" },
  { charge: "(11)17. Illegal Parking Of An Aircraft" },
  { charge: "(11)18. Tinted Windows" },
  { charge: "(11)19. Unlawful Transport of Persons in a Cargo Area" },
  { charge: "(11)20. Fire Hydrant Parking Restriction" },
  { charge: "(13)01. Tax Evasion***" },
  { charge: "(13)02. Laundering Of Money Instruments***" },
  { charge: "(13)03. Gambling License Violation" },
  { charge: "(13)04. Medical Practice Violation" },
  { charge: "(13)05. Legal Practice Violation" },
  { charge: "(13)06. Construction And Maintenance Code Violation " },
  { charge: "(13)07. Criminal Fire Code Violation" },
  { charge: "(13)08. Failure to Comply with Fire Code Orders " },
  { charge: "(13)09. Wiretapping Violation" },
  { charge: "(13)10. Criminal Business Operations" },
  { charge: "(13)11. Corporate Hijacking" }
];
